name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish for Windows
      run: dotnet publish -r win10-x64 --no-self-contained

  publish:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/main/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: /home/runner/work/FindReplaceText/FindReplaceText/bin/Release/net6.0/win10-x64/publish
        GITHUB_TOKEN: ${{ secrets.GIT_PAT }}



